version: "3.9"

services:
  mce:
    build:
      context: .
      dockerfile: Dockerfile
    image: mce:tui
    container_name: mce_tui
    tty: true
    stdin_open: true
    environment:
      TERM: xterm-256color
      MCE_HOST_ROOT: /host
      MCE_OUTPUT_ROOT: /host/c/Users/Itay_Vazana/Desktop/MCE_CPP/outputs  # (optional)
    volumes:
      - type: bind
        source: "C:\\"
        target: /host/c
      # - type: bind
      #   source: "D:\\"
      #   target: /host/d
